/**
 * Pull the look out of Quire Ink and into the Ghost theme, by RUNNING Quire Ink's own emitters.
 *
 * Nothing here retypes a colour, a size or a rule. `tools/tsconfig.json` maps `@/*` at the
 * sibling checkout, so every value below is the value the live site renders with; when the
 * blog's front end moves, this is re-run rather than re-read. The Quire Ink commit it was
 * taken from is written into the manifest, so a stale copy is a diff and not a guess.
 *
 * Emits, into quire-ink/:
 *   assets/css/quireink-base.css   the hand-written public sheet (PUBLIC_CSS), less the IDE chrome
 *   assets/css/quireink-ide.css    the IDE chrome, so it can be left unloaded when it is off
 *   assets/css/quireink-tokens.css palette + type scale + shape, for DEFAULT_SETTINGS
 *   assets/fonts/*.woff2           the self-hosted faces the default preset can reach
 *   assets/js/core.js, post.js     Quire Ink's own reader bundles, byte for byte
 *   ../tools/extract-manifest.json what came from where, and at which commit
 *
 * WHAT THE WORDPRESS EXTRACTOR EMITS AND THIS ONE DOES NOT, each for a reason:
 *   theme.json   a block-editor dialect. Ghost's editor is Koenig and reads no such file.
 *   editor.css   the same, aimed at a canvas that does not exist here.
 *   rtl.css      WordPress links `rtl.css` from the theme root for an RTL locale with no
 *                code of the theme's. Ghost has no such convention, so the sheet would need
 *                plumbing of its own — ADR 0003.
 *   appearance   ~15 KB of generated PHP for the Customizer. Ghost's theme settings are a
 *                short declarative list in package.json and cannot take a generated table.
 */
import { mkdir, writeFile, readdir, copyFile, rm } from 'node:fs/promises'
import { join, dirname } from 'node:path'
import { $ } from 'bun'

import { PUBLIC_CSS } from '@/web/public.css'
import { IDE_CSS } from '@/web/ide.css'

import { DEFAULT_SETTINGS } from '@/content/settings'
import {
  themesToCss, fontPresetCss, chromeFontCss, THEME_PRESETS, TYPE_ROLES,
} from '@/content/themes'
import { cjkLangCss } from '@/content/fonts'
import { typographyToCss, shapeToCss, tableToCss } from '@/content/settings'
import { allFontFaceCss, MONO_TRACKING } from '@/render/font-faces'
import { singleRailCss, timelineCss } from '@/render/rail-css'
import { t } from '@/i18n/i18n'
import { escapeAttr } from '@/utils'
import { ICONS } from '@/icons'

const HERE = dirname(import.meta.dir)
const QUIRE = join(HERE, '..', 'quireink')
// Normally the theme itself. `EXTRACT_OUT` points it elsewhere so
// `tools/checks/generated-in-sync.ts` can produce a fresh copy and compare bytes without
// touching what is committed — a check that has to modify the tree to run is a check people
// turn off.
const THEME = process.env.EXTRACT_OUT ?? join(HERE, 'quire-ink')

const s = DEFAULT_SETTINGS

// ---------------------------------------------------------------- the two sheets

// The order is `layout.ts`'s `pageStyles()`, which is load-bearing: --density must be
// declared before the block that multiplies it into --sp, and the palette before the type
// scale. Read the two side by side when either moves.
//
// Four entries of that list are left out, and all four for the same reason: on DEFAULT
// settings they emit the empty string — `selectionCss` and `penGesturesCss` only speak when
// an owner has changed an ink or switched a gesture off; `figureCss` and `galleryCss` say
// nothing when the site-wide frame is 'none', which is the default.
const tokens = [
  '/* Generated by tools/extract.ts — do not edit. Run `bun run extract`. */',
  allFontFaceCss(),
  // The three font HANDLES. `--font-reading` is what `.prose` asks for; with no declaration
  // the article falls back to the browser's serif while every other part looks correct.
  `:root{--font-sans:'Inter', 'Inter Fallback', system-ui, -apple-system, 'Segoe UI', sans-serif;`
    + `--font-reading:var(--font-sans);`
    + `--font-mono:'JetBrains Mono', ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace}`,
  // The reading column. `.wrap` reads `--shell-w` with a 42rem fallback, so a missing
  // declaration is not a broken page — it is a page that quietly ignores the setting.
  `:root{--shell-w:${s.contentWidth}px}`,
  // The desktop rail. Below the breakpoint `.rail` is a slide-out drawer, and ONLY these
  // generated rules promote it into the gutter. Generated rather than written because a
  // media query cannot read a CSS variable and the breakpoint is COMPUTED from the column
  // width — the rail moves out only when there is room on BOTH sides.
  singleRailCss(s.contentWidth),
  // The listing's gutter timeline: the spine, the sticky year tag and the month markers.
  // Its first line is `.tl-mark,.tl-year{display:none}`, so a page that never runs the
  // grouping script is invisible-fallback rather than wrong. That matters more here than on
  // WordPress: on Ghost the groups are built by script (ADR 0002).
  timelineCss(s.contentWidth),
  fontPresetCss(s.fontPreset),
  cjkLangCss(s.fontPreset),
  chromeFontCss(s.chromeFont),
  themesToCss(s.themes, s.themePreset, undefined, s.defaultScheme),
  shapeToCss(s.shape),
  tableToCss(s.table),
  typographyToCss(s.typography),
  MONO_TRACKING,
].filter(Boolean).join('\n')
  // Quire Ink serves its faces from the site root; a Ghost theme's files are served under
  // /assets/. Relative is the answer that needs no template: a url() in a stylesheet resolves
  // against THAT stylesheet, and both directories are siblings under assets/.
  .replaceAll("url('/fonts/", "url('../fonts/")

// The IDE chrome comes out into its own sheet, because it is the one part of the base sheet
// an owner can switch off — and switching it off should stop it being downloaded, not just
// stop it applying.
//
// It is LIFTED, never re-typed. `IDE_CSS` is a contiguous slice of `PUBLIC_CSS` and this
// removes exactly that slice; if the blog engine ever composes the sheet differently the
// slice stops matching and this throws, which is the seam reporting rather than a theme
// quietly shipping the chrome twice.
const IDE_SLICE = '\n' + IDE_CSS + '\n'
if (!PUBLIC_CSS.includes(IDE_SLICE)) {
  throw new Error(
    'IDE_CSS is no longer a contiguous slice of PUBLIC_CSS.\n'
    + '  Quire Ink has changed how src/web/public.css.ts composes the sheet.\n'
    + '  Read that file, then decide whether the IDE chrome can still be lifted out;\n'
    + '  do NOT paste the rules in here.',
  )
}

await mkdir(join(THEME, 'assets', 'css'), { recursive: true })
await writeFile(join(THEME, 'assets', 'css', 'quireink-base.css'),
  '/* Copied from Quire Ink src/web/*.css.ts by tools/extract.ts, less the IDE chrome,\n'
  + '   which is lifted whole into quireink-ide.css. */\n'
  + PUBLIC_CSS.replace(IDE_SLICE, '\n') + '\n')
await writeFile(join(THEME, 'assets', 'css', 'quireink-ide.css'),
  '/* Quire Ink src/web/ide.css.ts, lifted whole by tools/extract.ts. Loaded only when\n'
  + '   the theme setting is on. */\n' + IDE_CSS + '\n')
await writeFile(join(THEME, 'assets', 'css', 'quireink-tokens.css'), tokens + '\n')

// ---------------------------------------------------------------- the alias sheet
//
// Koenig's name for a thing, given the engine's own rule for that thing.
//
// This started life in `ghost-bridge.js`, adding Quire Ink's class beside Ghost's on the way
// past — the trick the WordPress port plays in a `render_block` filter. It was wrong here for
// a reason gscan said out loud: `.kg-width-wide` and `.kg-width-full` have to appear STYLED
// in a Ghost theme's CSS, and behind that rule is a reader with no JavaScript, for whom a
// wide figure was simply not wide. A layout that needs a script to be a layout is not one.
//
// So the rules are DERIVED instead. The engine's own declarations are lifted verbatim out of
// `PUBLIC_CSS` and re-emitted under Koenig's selector: one definition of what "wide" means,
// still upstream, and a re-extract carries any change across without anyone re-reading this.
//
// Each is scoped under `.prose` so it is 0,2,0 and outranks Ghost's own `.kg-*` card sheet,
// which `{{ghost_head}}` injects after everything this theme links.
const ALIASES: [string, string[]][] = [
  ['.img-wide', ['.kg-width-wide', '.kg-width-full']],
  ['.callout', ['.kg-callout-card']],
]

/**
 * Split a selector list on its TOP-LEVEL commas only.
 *
 * `.prose > :is(figure.img-wide,.video-wide):nth-child(-n+2)` is ONE selector with a comma
 * inside it. Split naively it becomes two fragments with unmatched parentheses, and a browser
 * silently drops a rule whose selector will not parse — so the rule is simply absent and
 * nothing anywhere says so.
 */
function splitSelectors(list: string): string[] {
  const out: string[] = []
  let depth = 0
  let current = ''
  for (const ch of list) {
    if (ch === '(' || ch === '[') depth++
    else if (ch === ')' || ch === ']') depth--
    if (ch === ',' && depth === 0) { out.push(current); current = ''; continue }
    current += ch
  }
  out.push(current)
  return out.map((x) => x.trim()).filter(Boolean)
}

function aliasSheet(sheet: string): { css: string; count: number } {
  // Comments first, and not as tidiness: the engine's sheet carries prose comments with
  // `.prose` and `.callout` inside them, and a selector regex run over the raw text pulled
  // half a sentence into a stylesheet. It parsed, it matched nothing, and it was visible only
  // by reading the generated file.
  const clean = sheet.replace(/\/\*[\s\S]*?\*\//g, '')

  const out: string[] = []
  let count = 0

  // At-rules are kept as CONTEXT rather than flattened. A rule that only applies inside a
  // media query, re-emitted without it, applies everywhere — which is a layout that is right
  // at one width and wrong at every other, and nothing about it looks wrong in a diff.
  const scan = (css: string, wrap: string[]): void => {
    const rule = /(@[a-z-]+[^{;]*)\{|([^{}@]+)\{([^{}]*)\}/gi
    let m: RegExpExecArray | null
    while ((m = rule.exec(css)) !== null) {
      if (m[1] !== undefined) {
        // An at-rule: find its matching brace and recurse with the condition pushed on.
        let depth = 1
        let i = rule.lastIndex
        while (i < css.length && depth > 0) {
          if (css[i] === '{') depth++
          else if (css[i] === '}') depth--
          i++
        }
        scan(css.slice(rule.lastIndex, i - 1), [...wrap, m[1]!.trim()])
        rule.lastIndex = i
        continue
      }
      const decls = (m[3] ?? '').trim()
      if (!decls) continue
      for (const [from, tos] of ALIASES) {
        const token = new RegExp(from.replace('.', '\\.') + '(?![\\w-])')
        const parts = splitSelectors(m[2]!).filter((x) => token.test(x))
        if (parts.length === 0) continue
        for (const to of tos) {
          const selectors = parts
            .map((x) => x.replace(new RegExp(token.source, 'g'), to))
            .map((x) => (x.includes('.prose') ? x : `.prose ${x}`))
          const body = `${selectors.join(',')}{${decls}}`
          out.push(wrap.length ? `${wrap.join('{')}{${body}${'}'.repeat(wrap.length)}` : body)
          count++
        }
      }
    }
  }

  scan(clean, [])
  return { css: out.join('\n'), count }
}

// BOTH HALVES, and missing the second one was a bug a reader could see. `singleRailCss()`
// redefines what a wide figure is once the contents rail is in the gutter — flush with the
// column on the left, nosing RIGHT by one rail width into the gutter the rail is not using,
// because the alternative collides with the rail. That rule is emitted into the tokens sheet
// rather than written in the static one, so scanning only `PUBLIC_CSS` produced a Koenig
// figure that still had symmetric negative margins and crossed the rail's own edge by 18px at
// 1440. Everything measured symmetric, which is exactly why it took an eye to catch.
const alias = aliasSheet([PUBLIC_CSS.replace(IDE_SLICE, '\n'), tokens].join('\n'))
if (alias.count === 0) {
  throw new Error('extract: no alias rules were produced.\n'
    + '  Quire Ink no longer carries .img-wide or .callout under those names,\n'
    + '  so a Koenig card has nothing to be given. Read src/web/prose.css.ts.')
}
await writeFile(join(THEME, 'assets', 'css', 'quireink-alias.css'),
  '/* Generated by tools/extract.ts. Do not edit.\n'
  + '   Quire Ink\'s own declarations, re-emitted under the class names Koenig writes. */\n'
  + alias.css + '\n')

// ---------------------------------------------------------------- the pen, deliberately absent
//
// Quire Ink's pen sheet is NOT emitted, for the reason the WordPress port gives: the strokes
// are 273 KB of generated SVG keyed on `data-pen` and `data-form`, attributes only Quire
// Ink's own editor produces. Koenig has no way to write one.

// ---------------------------------------------------------------- the faces

const FONT_SRC = join(QUIRE, 'src', 'assets', 'static', 'fonts')
const FONT_DST = join(THEME, 'assets', 'fonts')
await mkdir(FONT_DST, { recursive: true })
// Only the faces. `OFL.txt` lives in this directory and is NOT generated — it is the licence
// text the SIL Open Font License requires to travel with the font software, assembled from
// each family's own distribution. An earlier version of this line was `rm -rf` on the whole
// directory, which would have deleted it on the next run and shipped six OFL faces with no
// licence: a violation that no check Ghost or anybody else runs would have reported.
for (const stale of await readdir(FONT_DST)) {
  if (stale.endsWith('.woff2')) await rm(join(FONT_DST, stale))
}
const faces = (await readdir(FONT_SRC)).filter((f) => f.endsWith('.woff2'))
for (const f of faces) await copyFile(join(FONT_SRC, f), join(FONT_DST, f))

// Shipping the faces without it is a licence violation whatever else is green, so this stops
// the extract rather than letting a theme be built that cannot legally be published.
if (!process.env.EXTRACT_OUT && !(await Bun.file(join(FONT_DST, 'OFL.txt')).exists())) {
  throw new Error('extract: assets/fonts/OFL.txt is missing.\n'
    + '  The SIL Open Font License requires its text to travel with the font software.\n'
    + '  Rebuild it from each family\'s own distribution — see docs/release-checklist.md.')
}

// ---------------------------------------------------------------- the islands

// Quire Ink's own reader bundles, built by its `build:assets`. `core` is the chrome (palette
// switch, rail, search overlay, back-to-top, newsletter) and `post` is the article (table of
// contents scrollspy, book mode, lightbox, quote copy, resume). Copied rather than
// rewritten, which is the whole point — a second implementation of book mode would be a
// second thing to be wrong.
//
// FOUR of their features talk to endpoints Ghost does not have: `/api/search`,
// `/api/subscribe`, `/api/track` and `/api/comments`. A Ghost theme has no server side to
// answer them with, so `assets/js/ghost-bridge.js` — the one script this repository writes —
// intercepts those four requests before the bundles are loaded and answers them from Ghost's
// own APIs. The bundles stay byte-identical, and `check:generated` proves it.
const JS_SRC = join(QUIRE, 'src', 'assets', 'dist')
const JS_DST = join(THEME, 'assets', 'js')
await mkdir(JS_DST, { recursive: true })
const bundles = ['core.js', 'post.js']
for (const b of bundles) await copyFile(join(JS_SRC, b), join(JS_DST, b))

// ---------------------------------------------------------------- the words
//
// Every string the two bundles put on screen is read off a `data-` attribute on <body> at
// run time (`layout.ts`'s `Shell.bodyData`), so a bundle carries no locale table. On the
// blog engine the server writes them; a Ghost theme has no server, so they are baked into
// two generated partials here.
//
// GENERATED, not typed. `chromeLabels()` is the engine's own function and the article's
// extra keys are lifted from `article.ts`'s list, so the wording is the wording the blog
// itself ships and a change upstream arrives as a diff on the next extract. Typing them by
// hand is how a theme ends up announcing a button as "button": the bundle's `label()` is
// `dataset[key] ?? ''`, and a key nobody supplies is an empty aria-label rather than a
// missing translation.
const en = t('en') as unknown as Record<string, string>

/**
 * The label KEYS, read out of the engine's source rather than imported from it.
 *
 * `@/web/chrome` cannot be imported: it reaches `@/web/assets`, which imports the built
 * `sw.js`, and that file only exists after the engine's own `build:assets` has run — which
 * this repository must never do, because the engine is read only.
 *
 * So the two lists are PARSED. Every `key: s.something` line inside the function is a label;
 * `defaultScheme: settings.defaultScheme` and the `sw` spread are not, and both fall out for
 * free because neither reads from `s`. A label added upstream arrives on the next extract
 * without anybody noticing it was needed, which is the whole reason this is not a typed list.
 */
async function labelKeys(file: string, from: string, to: string): Promise<[string, string][]> {
  const src = await Bun.file(join(QUIRE, 'src', 'web', file)).text()
  const start = src.indexOf(from)
  if (start < 0) throw new Error(`extract: ${from} is no longer in src/web/${file}`)
  const end = src.indexOf(to, start)
  if (end < 0) throw new Error(`extract: ${to} no longer follows ${from} in src/web/${file}`)
  const block = src.slice(start, end)
  const out: [string, string][] = []
  for (const m of block.matchAll(/(\w+): s\.(\w+)\b/g)) out.push([m[1]!, m[2]!])
  if (out.length === 0) throw new Error(`extract: no labels found in src/web/${file}`)
  return out
}

const chromeKeys = await labelKeys('chrome.ts', 'export function chromeLabels', '\n}')
// The article's own additions. Every `comment*` key is dropped on purpose: Ghost has a
// comment thread of its own and this theme uses it, so the engine's comment island never
// mounts and supplying its strings would put words on the page for machinery that is not
// running.
const postKeys = (await labelKeys('article.ts', 'bodyData: {', 'scripts:'))
  .filter(([key]) => !key.startsWith('comment'))

/** `backToTop` -> `data-back-to-top`. The inverse of the browser's `dataset` mapping. */
const dataAttr = (key: string) => `data-${key.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}`

function attrs(pairs: [string, string][]): string {
  const seen = new Set<string>()
  const lines: string[] = []
  for (const [key, localeKey] of pairs) {
    if (seen.has(key)) continue
    seen.add(key)
    const value = en[localeKey]
    if (value === undefined) throw new Error(`extract: locales/en.ts has no ${localeKey}`)
    lines.push(` ${dataAttr(key)}="${escapeAttr(value)}"`)
  }
  return lines.join('\n')
}

await mkdir(join(THEME, 'partials'), { recursive: true })
await writeFile(join(THEME, 'partials', 'generated-labels.hbs'),
  "{{!-- Generated by tools/extract.ts from the engine's chromeLabels(). Do not edit. --}}\n"
  + attrs(chromeKeys) + '\n')
await writeFile(join(THEME, 'partials', 'generated-labels-post.hbs'),
  "{{!-- Generated by tools/extract.ts from the engine's article.ts. Do not edit. --}}\n"
  + attrs(postKeys) + '\n')

// The palette picker's rows ride on the button as `id:Name|id:Name`, which is the island's
// contract (`core.js` splits on `|` then on the first `:`). The ids are the presets the sheet
// actually carries and the names are the engine's own, so the two can never disagree about
// which palettes exist. It is interpolated straight into the button below rather than kept in
// a partial of its own: a partial would render a trailing newline INSIDE an attribute value,
// and a file nobody includes is the thing `check:generated` exists to catch.
const paletteNames = en.paletteNames as unknown as Record<string, string>
const paletteOptions = THEME_PRESETS
  .map((p) => `${p.id}:${paletteNames[p.id] ?? p.id}`)
  .join('|')

// ---------------------------------------------------------------- the header's controls
//
// `.site-actions` — the row of controls in the site bar — is emitted here rather than typed
// into a template, because every one of them is a contract with a bundle: the attribute the
// island looks for (`data-search-open`, `data-theme-toggle`, …), the icon, and the short
// bracketed token the IDE chrome shows instead of the icon. Typed out, the row is six
// chances to spell an attribute nearly right and get a control that renders and does
// nothing.
//
// What this repository DOES decide, and what is therefore written here rather than lifted:
// which controls a Ghost site can offer at all, and what they fall back to without
// JavaScript. The search trigger points at `#/search` (Ghost's own overlay) rather than the
// engine's `/search` page, which Ghost has no route for; the sign-up trigger is wrapped in
// `{{#if @site.members_enabled}}`, because on Ghost that is a site setting rather than
// whether a mail server answers.
//
// MARKED EXCEPTION to "nothing is hand-copied": the <svg> wrapper's own numbers and the
// `.btn-token` span are restated below. They are markup with two values in them, they live
// inside a function this file cannot import, and both are pinned by the assertion that
// follows — a change to either in the engine stops the extract rather than shipping a theme
// whose icons are a different weight from the blog's.
const chromeSrc = await Bun.file(join(QUIRE, 'src', 'web', 'chrome.ts')).text()
for (const pin of ['width="20" height="20" viewBox="0 0 24 24"', 'stroke-width="1.8"',
  'class="btn-token"']) {
  if (!chromeSrc.includes(pin)) {
    throw new Error(`extract: src/web/chrome.ts no longer contains ${pin}.\n`
      + '  The icon wrapper below is a marked copy of that markup and has drifted.\n'
      + '  Read siteHeader() there, then update this block to match.')
  }
}
const svg = (body: string) =>
  '<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor"'
  + ' stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
  + `${body}</svg>`
const btnToken = (text: string) => `<span class="btn-token">${escapeAttr(text)}</span>`

const iconBtn = (
  tag: 'a' | 'button',
  open: string,
  icon: string,
  short: string,
  label: string,
  extra = '',
) => `<${tag} ${tag === 'a' ? '' : 'type="button" '}class="icon-btn${
  open === 'data-rail-toggle' ? ' rail-toggle' : ''
}" ${open}${extra} aria-label="${escapeAttr(label)}" title="${escapeAttr(label)}">${
  svg(icon)}${btnToken(short)}</${tag}>`

const siteActions = [
  // A LINK, so it is not dead with scripting off: `#/search` is the address Ghost's own
  // search overlay answers. Our island intercepts the click first and opens the engine's.
  iconBtn('a', 'href="#/search" data-search-open', ICONS.search, en.shortSearch, en.search),
  iconBtn('button', 'data-theme-toggle', ICONS.theme, en.shortTheme, en.theme,
    ' aria-haspopup="true" aria-expanded="false"'),
  '{{#if @custom.reader_can_change_palette}}'
  + iconBtn('button',
    `data-palettes="${escapeAttr(paletteOptions)}" data-palette-default="{{@custom.palette}}"`,
    ICONS.palette, en.shortPalette, en.palette,
    ' aria-haspopup="true" aria-expanded="false"')
  + '{{/if}}',
  iconBtn('button', 'data-grid-toggle', ICONS.grid, en.shortGrid, en.gridView,
    ' aria-pressed="false"'),
  // Ghost's own sign-up, not the engine's: `#/portal/signup` is Portal's address, and the
  // island only takes the click over on a page that has the engine's card to open.
  '{{#if @site.members_enabled}}'
  + iconBtn('a', 'href="#/portal/signup" data-subscribe-open', ICONS.mail, en.shortMail,
    en.nlHeading)
  + '{{/if}}',
  iconBtn('button', 'data-rail-toggle', ICONS.menu, en.shortMenu, en.menu,
    ' aria-expanded="false"'),
].join('\n')

await writeFile(join(THEME, 'partials', 'generated-site-actions.hbs'),
  '{{!-- Generated by tools/extract.ts from the engine\'s siteHeader(). Do not edit. --}}\n'
  + siteActions + '\n')

// ---------------------------------------------------------------- the receipt

const sha = (await $`git -C ${QUIRE} rev-parse HEAD`.text()).trim()
const dirty = (await $`git -C ${QUIRE} status --porcelain`.text()).trim() !== ''
if (!process.env.EXTRACT_OUT) {
  await writeFile(join(HERE, 'tools', 'extract-manifest.json'), JSON.stringify({
    takenFrom: { repo: 'quireink', commit: sha, workingTreeDirty: dirty },
    emitted: {
      'quire-ink/assets/css/quireink-base.css': PUBLIC_CSS.length - IDE_CSS.length - 1,
      'quire-ink/assets/css/quireink-ide.css': IDE_CSS.length,
      'quire-ink/assets/css/quireink-tokens.css': tokens.length,
      'quire-ink/assets/css/quireink-alias.css': alias.css.length,
      'quire-ink/assets/fonts': faces.length,
      'quire-ink/assets/js': bundles,
    },
    palettes: THEME_PRESETS.map((p) => p.id),
    typeRoles: TYPE_ROLES,
    fontPreset: s.fontPreset,
    chromeFont: s.chromeFont,
    contentWidth: s.contentWidth,
  }, null, 2) + '\n')
}

console.log(`base   ${PUBLIC_CSS.length - IDE_CSS.length - 1} B (IDE chrome lifted out)`)
console.log(`ide    ${IDE_CSS.length} B`)
console.log(`tokens ${tokens.length} B`)
console.log(`fonts  ${faces.length} files`)
console.log(`js     ${bundles.join(', ')}`)
console.log(`alias  ${alias.count} rules, ${alias.css.length} B`)
console.log(`actions ${siteActions.split('icon-btn').length - 1} controls`)
console.log(`labels ${chromeKeys.length} chrome + ${postKeys.length} article, ${THEME_PRESETS.length} palettes`)
console.log(`from   quireink@${sha.slice(0, 7)}${dirty ? ' (dirty)' : ''}`)
